"""Add generating_status to weekly_menus

Revision ID: 5348c8791737
Revises: 708a3d3bc727
Create Date: 2026-02-01 14:17:47.273752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5348c8791737'
down_revision = '708a3d3bc727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generating_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_menus', schema=None) as batch_op:
        batch_op.drop_column('generating_status')

    # ### end Alembic commands ###
