"""Add production management tables

Revision ID: 708a3d3bc727
Revises: 
Create Date: 2026-01-29 17:59:08.687056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708a3d3bc727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('last_in_date', sa.Date(), nullable=True),
    sa.Column('last_out_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id')
    )
    op.create_table('stock_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('in_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('scale_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_menu_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_menu_id'], ['weekly_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_menu_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('dish_name', sa.String(length=128), nullable=False),
    sa.Column('dish_category', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weekly_menu_id'], ['weekly_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('sub_menu_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_menu_id'], ['sub_menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('sub_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_menu_id', sa.Integer(), nullable=False),
    sa.Column('weekly_menu_item_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('dish_name', sa.String(length=128), nullable=False),
    sa.Column('dish_category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sub_menu_id'], ['sub_menus.id'], ),
    sa.ForeignKeyConstraint(['weekly_menu_item_id'], ['weekly_menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.Column('use_stock', sa.Boolean(), nullable=True),
    sa.Column('purchase_quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('out_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=128), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('scale_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_outs')
    op.drop_table('purchase_order_items')
    op.drop_table('sub_menu_items')
    op.drop_table('purchase_orders')
    op.drop_table('weekly_menu_items')
    op.drop_table('sub_menus')
    op.drop_table('weekly_menus')
    op.drop_table('stock_ins')
    op.drop_table('inventories')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
